version: "3.9"

services:

  gateway:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: luizmiguelvb/gateway
    container_name: gateway
    ports:
      - "8082:8082"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    networks:
      - gestao-mercados-microsservices-bridge

networks:
  gestao-mercados-microsservices-bridge:
    driver: bridge
    external: true